### PR TITLE
oh boy here are my 8am no-sleep tweaks

### PR DESCRIPTION
**Pull request by t5r7**
- lighten some of the colours a bit (improves the contrast but it's a bit uh, pink)
- make the SCSS more SCSS-y (nesting and &-rules)
- implement post categories properly
- add post archive page making use of the better categories

### CODE REVIEW

**Comment by t5r7** [comment]
oh bruh vercel is neat i didnt know it did that


how long before i switch to some CI thing too instead of straight github pages

**Comment by htbrown** [comment]
Will get round to merging this at some point; some things need changing so I'll have to merge into a separate branch and that requires effort.

**Comment by t5r7** [comment]
imagine putting in effort cannot relate

________________________________

**Comment by htbrown** [comment]
Gonna close this and make changes to the repo that basically reflect it. Expect questions because of my awful SCSS skills and Jekyll knowledge.

**Comment by t5r7** [comment]
🙏🏻

________________________________

**Pull request closed without merging**
